spring:
  application:
    name: cyj-discovery
  profiles:
    active: dev
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: false
    registerWithEureka: false