POST http://localhost:8030/dictionaryApi/findCatalogById?id=1
Accept: application/json

###
POST http://localhost:8030/dictionaryApi/dictionaryCatalogFindAll
Content-Type: application/json

###
POST http://localhost:8030/dictionaryApi/saveDictionaryCatalog
Content-Type: application/json

{
  "catalogName": "5555",
  "catalogValue": "5555",
  "description": "5555"
}

###
POST http://localhost:8030/dictionaryApi/findDictionaryByCatalogValueAndDictionaryKey
Content-Type: application/x-www-form-urlencoded

value=YES_NO&key=Y

###


