server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
zuul:
  routes: #给服务配置路由
    cyj-dictionary:
      path: /cyj-dictionary/**
    cyj-entity-creater:
      path: /cyj-entity-creater/**
    cyj-auth:
      path: /cyj-auth/**
    cyj-user:
      path: /cyj-user/**
spring:
  application:
    name: cyj-user
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 68762306
  cloud:
    stream:
      bindings:
        greetingChannel:
          destination: greetings
security:
  loginAfterTime: 10
  loginTimeLimit: 10
#feign的配置，连接超时及读取超时配置
feign:
  client:
    default-config: my-config
    config:
      my-config:
        connectTimeout: 6000000
        readTimeout: 6000000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000000000
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
